version: "2.3"
services:
  gateway:
    image: nginx:1.11
    ports:
      - 4000:4000
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - user_service
      - notification_service
  user_service:
    container_name: user_service
    restart: unless-stopped
    build: ./user/
    ports:
      - "4001:4001"
    links:
      - user_service_mongo
    environment:
      PORT: 4001
      MONGO_HOSTNAME: "user_service_mongo"
      MONGO_PORT: ${MONGO_PORT}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_DB: ${MONGO_DB}
      SUPER_ADMIN_PASSWORD: ${SUPER_ADMIN_PASSWORD}
      SUPER_ADMIN_EMAIL: ${SUPER_ADMIN_EMAIL}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      JWT_SECRET: ${JWT_SECRET}
      AUTH_SOURCE: ${AUTH_SOURCE}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      RESET_PASSWORD_URL: http://localhost:4000/api/v1/users/password/reset
      PHONE: ${PHONE}

  user_service_mongo:
    container_name: user_service_mongo
    restart: unless-stopped
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_DB: ${MONGO_DB}
      SUPER_ADMIN_PASSWORD: ${SUPER_ADMIN_PASSWORD}
      SUPER_ADMIN_EMAIL: ${SUPER_ADMIN_EMAIL}
    expose:
      - "27017"
    ports:
      - "27018:27017"
    volumes:
      - ./user/data:/data/db
      - ./user/docker-entrypoint:/docker-entrypoint-initdb.d/

  notification_service:
    container_name: notification_service
    restart: unless-stopped
    build: ./notification/
    ports:
      - "4002:4002"
    links:
      - notification_service_mongo
    environment:
      PORT: 4002
      MONGO_HOSTNAME: "notification_service_mongo"
      MONGO_PORT: ${MONGO_PORT}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_DB: ${MONGO_DB}
      SUPER_ADMIN_PASSWORD: ${SUPER_ADMIN_PASSWORD}
      SUPER_ADMIN_EMAIL: ${SUPER_ADMIN_EMAIL}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      JWT_SECRET: ${JWT_SECRET}
      AUTH_SOURCE: ${AUTH_SOURCE}
      VONAGE_API_KEY: ${VONAGE_API_KEY}
      VONAGE_API_SECRET: ${VONAGE_API_SECRET}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      GETUSERURI: "http://user_service:4001/users"

  notification_service_mongo:
    container_name: notification_service_mongo
    restart: unless-stopped
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_DB: ${MONGO_DB}
      SUPER_ADMIN_PASSWORD: ${SUPER_ADMIN_PASSWORD}
      SUPER_ADMIN_EMAIL: ${SUPER_ADMIN_EMAIL}
    expose:
      - "27017"
    ports:
      - "27019:27017"
    volumes:
      - ./notification/data:/data/db
      - ./notification/docker-entrypoint:/docker-entrypoint-initdb.d/
